let num1=prompt("enter the first number");
let num2=prompt("enter the second number");
let num3=prompt("enter the third number");
let num4=prompt("enter the fourth number");
let num5=prompt("enter the fifth number");
let sum=num1+num2+num3+num4+num5;
let value=5;
average=sum/value;
console.log(sum);
console.log(average);